# Generated by Django 3.0.5 on 2020-04-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('host', models.CharField(blank=True, default='', max_length=100)),
                ('prize', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('eventId', models.CharField(blank=True, default='', max_length=50)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('location', models.TextField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=800)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(null=True, upload_to='hackathon_pics')),
                ('challenges', models.ManyToManyField(blank=True, to='central.Challenge')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(blank=True, default='', max_length=50)),
                ('members', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.Hackathon')),
            ],
        ),
    ]
