# Generated by Django 2.2.5 on 2020-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveSmallIntegerField()),
                ('name', models.TextField()),
                ('srn', models.CharField(max_length=15)),
                ('att', models.BooleanField()),
            ],
        ),
    ]
