# Generated by Django 2.2.5 on 2020-01-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Student',
        ),
    ]
