# Generated by Django 3.0.5 on 2020-04-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=30, null=True)),
                ('devpost', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('skillset', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.CharField(choices=[('New', 'New hacker'), ('Developer', 'Developer'), ('Business', 'Business'), ('Designer', 'Designer')], default='New', max_length=15)),
                ('bio', models.TextField(blank=True, default='', max_length=900)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
