# Generated by Django 2.2.5 on 2020-03-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveSmallIntegerField()),
                ('name', models.TextField()),
                ('srn', models.CharField(max_length=15)),
                ('att', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
