# Generated by Django 2.2.5 on 2020-03-12 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('uni', models.CharField(max_length=15)),
                ('number_of_members', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(5)])),
                ('boarding', models.BooleanField()),
            ],
        ),
    ]
